Calculator-Salar-WebApp/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;


namespace Calculator_Salar_WebApp.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }
        public DbSet<NetSalaryCalculator> NetSalariesCalculator { get; set; }
        public DbSet<GrossSalaryCalculator> GrossSalariesCalculator { get; set; }

    }
}

Calculator-Salar-WebApp/Models/ErrorViewModel.cs
using System;

namespace Calculator_Salar_WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Calculator-Salar-WebApp/Models/GrossSalaryCalculator.cs
namespace Calculator_Salar_WebApp.Models
{
    public class GrossSalaryCalculator
    {
        public int Id { get; set; }
        public uint GrossSalary { get; set; }
        public uint Cas { get; set; }
        public uint Cass { get; set; }
        public uint TaxableBase { get; set; }
        public uint Tax { get; set; }
        public uint NetSalary { get; set; }

    }
}

Calculator-Salar-WebApp/Models/NetSalaryCalculator.cs
using System.ComponentModel.DataAnnotations;


namespace Calculator_Salar_WebApp.Models
{
    public class NetSalaryCalculator
    {
        public int Id { get; set; }

        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Salariul brut nu poate avea valoarea 0 sau mai mica decat 0! Te rog reincearca.")]
        [Display(Name = "Salar Brut")]
        public uint GrossSalary { get; set; }

        [Display(Name = "CAS")]
        public uint Cas { get; set; }

        [Display(Name = "CASS")]
        public uint Cass { get; set; }

        [Display(Name = "Venit Impozabil")]
        public uint TaxableBase { get; set; }

        [Display(Name = "Impozit")]
        public uint Tax { get; set; }

        [Display(Name = "Salar Net")]
        public uint NetSalary { get; set; }

    }
}

Calculator-Salar-WebApp/Controllers/GrossSalaryCalculatorController.cs
using Microsoft.AspNetCore.Mvc;

namespace Calculator_Salar_WebApp.Controllers
{
    public class GrossSalaryCalculatorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Calculator-Salar-WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Calculator_Salar_WebApp.Models;

namespace Calculator_Salar_WebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Calculator-Salar-WebApp/Controllers/NetSalaryCalculatorController.cs
using Calculator_Salar_WebApp.Models;
using Calculator_Salar_WebApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace Calculator_Salar_WebApp.Controllers
{
    public class NetSalaryCalculatorController : Controller
    {
        private readonly ApplicationDbContext _context;
        public NetSalaryCalculatorController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index([Bind("GrossSalary")] NetSalaryCalculator _grossSalary)
        {
            if (ModelState.IsValid && _grossSalary != null)
            {
                var calculationResult = Formulas.ForNetSalaryAndEmployeeTaxesCalculationFromGrossSalary(_grossSalary);
                SaveResultsInDB(calculationResult);
                return RedirectToAction(nameof(CompleteCalculation), "NetSalaryCalculator", calculationResult);
            }
            return View(_grossSalary);
        }

        private void SaveResultsInDB(NetSalaryCalculator result)
        {
            _context.NetSalariesCalculator.Add(result);
            _context.SaveChanges();
        }

        public IActionResult CompleteCalculation(NetSalaryCalculator calculationResult)
        {
            return View(calculationResult);
        }

    }
}

Calculator-Salar-WebApp/Views/GrossSalaryCalculator/Index.cshtml
@model GrossSalaryCalculator

@{
    ViewData["Title"] = "Calculator salariu brut";
}

<div class="container">

    <h1 style="color:darkgoldenrod; text-align:center"><b>Calculator salariu brut</b></h1>
    <p style="color:darkgrey; text-align:center">Calculator salariu aplica reglementarile anului fiscal 2019/2020, ultima actualizare fiind pe 7 ianuarie 2019.</p>
    <br />
    <form style="color:darkgoldenrod; text-align:center" class="form-inline" action="/action_page.php">
        <div class="form-group">
            <input asp-for="NetSalary" class="form-control" placeholder="Introduceti salariul net" />
            <span asp-validation-for="NetSalary" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-warning">Calculeaza</button>
    </form>
</div>

Calculator-Salar-WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

Calculator-Salar-WebApp/Views/NetSalaryCalculator/CompleteCalculation.cshtml
@model NetSalaryCalculator

<div class="container" style="padding-top:80px;">
    <h1 style="color:darkgoldenrod; text-align:center"><b>Calcul salariu net 2020</b></h1>
    <p style="color:darkgrey; text-align:center">Vizualizati fluturasul de salariu cu toate contributiile la stat.</p>
    <br />

    <table class="table">
        <thead style="color:aliceblue; font-size: 30px">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.GrossSalary)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NetSalary)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cas)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cass)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TaxableBase)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tax)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody style="color:darkgoldenrod; font-size: 30px; font-weight: 900;">
            <tr>
                <td>
                    @Html.DisplayFor(model => model.GrossSalary)
                </td>
                <td>
                    @Html.DisplayFor(model => model.NetSalary)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Cas)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Cass)
                </td>
                <td>
                    @Html.DisplayFor(model => model.TaxableBase)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Tax)
                </td>
            </tr>

        </tbody>
    </table>
</div>

Calculator-Salar-WebApp/Views/NetSalaryCalculator/Index.cshtml
@model NetSalaryCalculator


<div class="container" style="padding-top:80px;">
    <h1 style="color:darkgoldenrod; text-align:center"><b>Calculator salariu net</b></h1>
    <p style="color:darkgrey; text-align:center">Calculator salariu aplica reglementarile anului fiscal 2020, ultima actualizare fiind pe 7 ianuarie 2019.</p>
    <br />
    <form asp-controller="NetSalaryCalculator" asp-action="Index" method="post" role="form" style="color:darkgoldenrod; text-align:center" class="form-inline">
        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="form-group">
            <input asp-for="GrossSalary" class="form-control" placeholder="Introduceti salariul brut" />
            @*<span asp-validation-for="SalarBrut" class="text-danger"></span>*@
        </div>
        <button type="submit" class="btn btn-warning">Calculeaza</button>
    </form>
</div>

Calculator-Salar-WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/content/site.css" />
    <title>Salary Calculator</title>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index" class="navbar-brand">Home</a></li>
                    <li><a asp-controller="NetSalaryCalculator" asp-action="Index" class="navbar-brand">Calculator salariu net</a></li>
                    @*<li><a asp-controller="GrossSalaryCalculator" asp-action="Index" class="navbar-brand">Calculator salariu brut</a></li>*@
                </ul>
            </div>
        </div>
    </nav>


    <div class="container body-content">
        @RenderBody()
    </div>


    @RenderSection("Scripts", required: false)
</body>
</html>